const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),room=params.get('room'),roomKey=`amu-summon-room-${room||1}`;let state={userName:'',monsters:[]},touch=null,place=null,voiceDone=false,candidate=null,recordTimer=null;const fixedStatNames=['攻撃力','体力','命中率','回心率'];
try{state=JSON.parse(localStorage.getItem(roomKey))||state}catch{};state.selectedMonsterId??=null;const save=()=>localStorage.setItem(roomKey,JSON.stringify(state));
function show(id){['admin','register','main','summonView','resultView','warehouseView','battleView'].forEach(x=>$(x)?.classList.toggle('hidden',x!==id))}
function monsterCard(m){const n=m.imageNumber||1;return `<div class="monster-title-row"><h2 class="name">${m.name}</h2><span class="qr-wrap"><canvas class="monster-qr" data-monster-qr="${encodeURIComponent(JSON.stringify({type:'amu-monster-battle',name:m.name,imageNumber:n,feeling:m.feeling||'元気',stats:m.stats||[]}))}"></canvas></span></div><img class="monster-img" src="進化モンスター/モンスター${n}/1.png" alt="${m.name}"><div class="mood">今の気持ち：${m.feeling||'元気'}</div><div class="stats">${(m.stats||GAME_DATA.stats.slice(0,4).map(name=>({name,value:50}))).map(s=>`<div class="stat">${s.name}：${s.value}<div class="bar"><div class="fill" style="width:${s.value}%"></div></div></div>`).join('')}</div>`}
function monsterId(m,i){return m.id||(m.id=`${Date.now()}-${i}-${Math.random().toString(36).slice(2)}`)}
function renderMain(){show('main');$('breederName')?.remove();$('main').insertAdjacentHTML('afterbegin',`<div id="breederName" class="breeder">召喚士：${state.userName}</div>`);const m=state.monsters.find(x=>monsterId(x,0)===state.selectedMonsterId)||state.monsters.at(-1);if(m)state.selectedMonsterId=monsterId(m,0);$('mainMonster').innerHTML=m?monsterCard(m):'<p class="empty">まだモンスターがいません。</p>';$('collectionCount').textContent=`モンスター：${state.monsters.length} / 10`;save()}
function renderWarehouse(){show('warehouseView');$('warehouseCount').textContent=`モンスター倉庫：${state.monsters.length}匹（表示するモンスターを選択）`;$('warehouseGrid').innerHTML=state.monsters.length?state.monsters.map((m,i)=>{const id=monsterId(m,i),selected=id===state.selectedMonsterId;return `<article class="monster-card ${selected?'selected':''}">${monsterCard(m)}<button class="select-monster" data-monster-id="${id}">${selected?'メイン画面に表示中':'メイン画面に表示する'}</button></article>`}).join(''):'<p class="empty">倉庫は空です。</p>';$('warehouseGrid').querySelectorAll('.select-monster').forEach(b=>b.onclick=()=>{state.selectedMonsterId=b.dataset.monsterId;save();renderMain()})}
function renderResult(){show('resultView');$('resultMonster').innerHTML=monsterCard(candidate);$('resultNotice').textContent='モンスターが召喚されました。所持しますか？';$('resultActions').innerHTML='<button id="keepMonster" class="big-button summon">所持する</button>';$('keepMonster').onclick=()=>{candidate.id=`${Date.now()}-${Math.random().toString(36).slice(2)}`;state.monsters.push(candidate);state.selectedMonsterId=candidate.id;save();renderMain()}}
function rooms(){const l=$('roomList');if(!l)return;l.innerHTML=Array.from({length:10},(_,i)=>{const n=i+1,s=JSON.parse(localStorage.getItem(`amu-summon-room-${n}`)||'{}');return `<div class="room-row"><a class="room-link" href="?room=${n}">${n}　${s.userName?`使用中：${s.userName}`:'空いている'}</a></div>`}).join('')}
function resetSummon(){touch=null;place=null;voiceDone=false;candidate=null;clearInterval(recordTimer);recordTimer=null;const old=$('summonStage');if(old)old.replaceWith(old.cloneNode(false));$('summonStage').innerHTML='<div id="touchDot" class="touch-dot hidden"></div><div id="touchCoordinate" style="position:absolute;left:8px;bottom:8px;padding:6px;background:#fff;border-radius:7px;font-weight:800;font-size:12px">タッチ位置：未指定</div>';if(!$('touchConfirm'))$('summonStage').insertAdjacentHTML('afterend','<button id="touchConfirm" class="big-button summon" disabled>生体エネルギーを確定する</button>');$('touchConfirm').disabled=true;$('touchConfirm').textContent='生体エネルギーを確定する';$('touchConfirm').style.background='';$('chooseLocation').disabled=true;$('chooseLocation').textContent='ここにする';$('chooseLocation').style.background='';$('spellButton').disabled=true;$('spellButton').textContent='呪文を唱える（3秒録音）';$('spellButton').style.background='';$('summonButton')?.remove();$('spellStep').insertAdjacentHTML('afterend','<section id="summonStep4" class="ritual-step" style="margin-top:42px"><h2>④召喚する</h2><p id="summonStatus" class="sensor">①〜③をすべて確定してください。</p><button id="summonButton" class="big-button summon" disabled>召喚する</button></section>');$('sensorText').textContent='五芒星に指を置いてください。音声の説明は表示しません。';navigator.mediaDevices?.getUserMedia({audio:true}).catch(()=>{});navigator.geolocation?.getCurrentPosition(p=>setMap(p.coords.latitude,p.coords.longitude),()=>{});setMap(35.68,139.73);bindTouch();bindFlow()}
function setMap(lat,lon){const area=$('mapArea');area.style.position='relative';area.style.aspectRatio='1';area.style.height='min(88vw,420px)';$('locationMap').style.pointerEvents='none';$('locationMap').src=`https://www.openstreetmap.org/export/embed.html?bbox=${lon-.005}%2C${lat-.005}%2C${lon+.005}%2C${lat+.005}&layer=mapnik`;let layer=$('mapMarkers');if(!layer){area.insertAdjacentHTML('beforeend','<div id="mapMarkers"></div>');layer=$('mapMarkers')}layer.innerHTML='';layer.style.cssText='position:absolute;inset:0;z-index:20;pointer-events:none';[[50,50],[20,20],[43,18],[72,24],[84,43],[24,48],[68,42],[78,72],[18,78],[47,82]].forEach((p,i)=>{const b=document.createElement('button');b.textContent='●';b.style.cssText=`position:absolute;left:${p[0]}%;top:${p[1]}%;border:2px solid #241238;border-radius:50%;width:28px;height:28px;padding:0;background:${i?'#63c985':'#f35a9e'};color:${i?'#63c985':'#f35a9e'};font-size:18px;pointer-events:auto`;b.onclick=()=>{document.querySelectorAll('#mapMarkers button').forEach(x=>{x.style.background='#63c985';x.style.color='#63c985'});b.style.background='#f35a9e';b.style.color='#f35a9e';place=i;$('locationText').textContent=`選択した場所：マーカー${i+1}`;$('chooseLocation').disabled=false};layer.appendChild(b)});place=0;$('locationText').textContent='現在地を選択中（ピンク）';$('chooseLocation').disabled=false}
function bindTouch(){const s=$('summonStage');const f=e=>{const p=e.touches?.[0]||e,r=s.getBoundingClientRect();touch={x:Math.max(0,Math.min(1,(p.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(p.clientY-r.top)/r.height)),pressure:p.pressure||p.force||.5};$('touchDot').style.left=`${touch.x*100}%`;$('touchDot').style.top=`${touch.y*100}%`;$('touchDot').classList.remove('hidden');$('touchDot').style.animation='energy .8s ease-in-out infinite';$('touchCoordinate').textContent=`指定位置：X ${Math.round(touch.x*100)}% / Y ${Math.round(touch.y*100)}%　圧力 ${touch.pressure.toFixed(2)}`;$('touchConfirm').disabled=false;e.preventDefault?.()};s.addEventListener('pointerdown',f);s.addEventListener('touchstart',f,{passive:false})}
function bindFlow(){$('touchConfirm').onclick=()=>{if(!touch)return;$('touchConfirm').disabled=true;$('touchConfirm').textContent='生体エネルギー読み込み完了';$('touchConfirm').style.background='#79d98b';$('sensorText').textContent='生体エネルギー読み込み完了'};$('chooseLocation').onclick=()=>{if(place===null)return;$('chooseLocation').disabled=true;$('chooseLocation').textContent='場所を確定しました';$('chooseLocation').style.background='#79d98b';$('spellButton').disabled=false};$('spellButton').onclick=()=>{if(!touch||place===null)return;$('spellButton').disabled=true;$('spellText').textContent='3秒間録音中…';const canvas=$('waveform'),ctx=canvas.getContext('2d'),timer=setInterval(()=>{ctx.clearRect(0,0,canvas.width,canvas.height);ctx.beginPath();for(let x=0;x<canvas.width;x+=4)ctx.lineTo(x,canvas.height/2+Math.sin(x/10+Date.now()/80)*25);ctx.strokeStyle='#ffec83';ctx.stroke()},80);setTimeout(()=>{clearInterval(timer);voiceDone=true;$('spellButton').textContent='詠唱完了・登録完了';$('spellButton').style.background='#79d98b';$('summonButton').disabled=false;$('summonStatus').textContent='①〜③の登録完了。召喚できます'},3000)};$('summonButton').onclick=()=>{if(!touch||place===null||!voiceDone)return;candidate={name:GAME_DATA.names[Math.floor(Math.random()*GAME_DATA.names.length)],imageNumber:1+Math.floor(Math.random()*65),feeling:GAME_DATA.feelings[Math.floor(Math.random()*GAME_DATA.feelings.length)],stats:GAME_DATA.stats.slice(0,4).map(name=>({name,value:10+Math.floor(Math.random()*91)}))};renderResult()}}
function startSummon(){show('summonView');resetSummon();$('summonStage').style.backgroundImage="url('指をおく背景.jpg')";$('summonStage').style.backgroundSize='cover'}
rooms();$('openSummon').onclick=startSummon;$('openWarehouse').onclick=renderWarehouse;$('cancelSummon').onclick=renderMain;$('backAdmin').onclick=()=>location.href=location.pathname;$('userNameInput').oninput=e=>$('registerUser').disabled=!e.target.value.trim();$('registerUser').onclick=()=>{state.userName=$('userNameInput').value.trim();save();renderMain()};document.querySelectorAll('[data-back-main]').forEach(b=>b.onclick=renderMain);if(room){if(state.userName)renderMain();else show('register')}else show('admin');
const cleanStart=startSummon;startSummon=function(){$('summonStep4')?.remove();cleanStart()};$('openSummon').onclick=startSummon;
function generateQRs(){document.querySelectorAll('[data-monster-qr]').forEach(c=>{const box=c.parentElement,text=decodeURIComponent(c.dataset.monsterQr);box.innerHTML='';try{if(typeof QRCode==='undefined')throw new Error('QR library unavailable');new QRCode(box,{text,width:68,height:68,colorDark:'#241238',colorLight:'#ffffff'})}catch{const img=document.createElement('img');img.alt='対戦用QRコード';img.src=`https://api.qrserver.com/v1/create-qr-code/?size=68x68&data=${encodeURIComponent(text)}`;box.appendChild(img)}})}
function monsterPower(m){return (m.stats||[]).reduce((sum,s)=>sum+Number(s.value||0),0)+Number(m.imageNumber||0)}
let battleStream=null,battleTimer=null;
async function openBattle(){show('battleView');$('battleResult').classList.add('hidden');$('battleStatus').textContent='相手のQRコードをカメラに見せてください。';try{if(!('BarcodeDetector' in window)){throw new Error('unsupported')}battleStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});$('battleVideo').srcObject=battleStream;const detector=new BarcodeDetector({formats:['qr_code']});battleTimer=setInterval(async()=>{try{const codes=await detector.detect($('battleVideo'));if(codes[0]?.rawValue){const enemy=JSON.parse(codes[0].rawValue);if(enemy.type==='amu-monster-battle')finishBattle(enemy)}}catch{}},500)}catch{$('battleStatus').textContent='このブラウザではQR読み取りに対応していません。EdgeまたはChromeで開いてください。'}}
function finishBattle(enemy){clearInterval(battleTimer);battleStream?.getTracks().forEach(t=>t.stop());const me=state.monsters.find(x=>monsterId(x,0)===state.selectedMonsterId)||state.monsters.at(-1);const myPower=monsterPower(me||{}),enemyPower=monsterPower(enemy),result=myPower===enemyPower?'引き分け！':myPower>enemyPower?'勝利！':'敗北…';$('battleStatus').textContent='対戦結果';$('battleResult').innerHTML=`<strong>${result}</strong><br><small>自分：${myPower}　相手：${enemyPower}</small>`;$('battleResult').classList.remove('hidden')}
function closeBattle(){clearInterval(battleTimer);battleStream?.getTracks().forEach(t=>t.stop());battleStream=null;show('main')}
const oldRenderMain=renderMain,oldRenderWarehouse=renderWarehouse;renderMain=()=>{oldRenderMain();generateQRs()};renderWarehouse=()=>{oldRenderWarehouse();generateQRs()};$('openBattle').onclick=openBattle;$('battleBack').onclick=closeBattle;$('openWarehouse').onclick=renderWarehouse;$('openSummon').onclick=startSummon;generateQRs();

// あむガチバトル新UI：緑・黄色テーマと、画像1枚でのモンスター発行
const newUiStyle=document.createElement('style');newUiStyle.textContent=`:root{--ink:#173b2b!important;--gold:#ffe26a!important;--green:#43b86b!important}body{color:#173b2b!important;background:linear-gradient(135deg,#d9f6bd,#fff6a8 55%,#b9e8ad)!important}.card,.monster-card{background:#fffef2!important;border-color:#125b3c!important}.big-button,.small,.room-link,.select-monster{border-color:#125b3c!important}.summon,.issue{background:#43b86b!important;color:#fff!important}.warehouse,.room-link{background:#ffe26a!important;color:#173b2b!important}.battle{background:#125b3c!important;color:#ffe26a!important}.mood{background:#e7f8d9!important}.fill{background:linear-gradient(90deg,#43b86b,#ffe26a)!important}.name{color:#125b3c!important}.summon-stage,.wave-panel,.ritual-step{background:#e7f8d9!important;border-color:#43b86b!important}`;document.head.appendChild(newUiStyle);
function applyTrainerWords(){const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{n.nodeValue=n.nodeValue.replaceAll('召喚士','トレーナー').replaceAll('召喚画面','モンスター発行画面').replaceAll('召喚の儀式','モンスター発行画面').replaceAll('召喚結果','発行完了').replaceAll('召喚する','モンスターを発行').replaceAll('召喚成功','モンスター発行成功')})}
function startMonsterIssue(){show('summonView');const view=$('summonView');view.innerHTML=`<h1>モンスター発行画面</h1><p class="sub">画像を1枚撮影すると、モンスターを1匹発行できます。</p><div class="issue-panel" style="padding:18px;border:2px solid #43b86b;border-radius:15px;background:#e7f8d9"><video id="issueVideo" autoplay playsinline style="display:block;width:100%;aspect-ratio:4/3;object-fit:cover;border:3px solid #125b3c;border-radius:14px;background:#173b2b"></video><canvas id="issueCanvas" class="hidden"></canvas><img id="issuePreview" class="hidden" style="display:block;width:100%;aspect-ratio:4/3;object-fit:contain;border:3px solid #125b3c;border-radius:14px;background:#d9f6bd"><div style="display:grid;gap:9px;margin-top:12px"><button id="takeIssuePhoto" class="big-button summon">📸 画像を撮影する</button><label class="big-button warehouse" style="text-align:center">画像を選択<input id="issueFile" type="file" accept="image/*" capture="environment" hidden></label></div><p id="issueStatus" class="sensor">カメラを起動しています。</p></div><button id="issueSubmit" class="big-button summon" disabled style="margin-top:18px">モンスターを発行する</button><button id="issueCancel" class="small" style="margin-top:12px">メイン画面へ戻る</button>`;let stream=null,imageData='';const video=$('issueVideo'),preview=$('issuePreview'),submit=$('issueSubmit'),status=$('issueStatus');const setImage=src=>{imageData=src;preview.src=src;preview.classList.remove('hidden');video.classList.add('hidden');submit.disabled=false;status.textContent='画像を確認して、モンスターを発行してください。';stream?.getTracks().forEach(t=>t.stop())};navigator.mediaDevices?.getUserMedia({video:{facingMode:'environment'},audio:false}).then(s=>{stream=s;video.srcObject=s;status.textContent='撮影ボタンを押してください。'}).catch(()=>{status.textContent='カメラが使えない場合は、画像を選択してください。'});$('takeIssuePhoto').onclick=()=>{if(!video.videoWidth)return;const c=$('issueCanvas');c.width=480;c.height=Math.round(video.videoHeight*480/video.videoWidth);c.getContext('2d').drawImage(video,0,0,c.width,c.height);setImage(c.toDataURL('image/jpeg',.78))};$('issueFile').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>setImage(r.result);r.readAsDataURL(f)};submit.onclick=()=>{candidate={name:GAME_DATA.names[Math.floor(Math.random()*GAME_DATA.names.length)],imageData,feeling:'元気',stats:GAME_DATA.stats.slice(0,4).map(name=>({name,value:10+Math.floor(Math.random()*91)}))};stream?.getTracks().forEach(t=>t.stop());renderResult()};$('issueCancel').onclick=()=>{stream?.getTracks().forEach(t=>t.stop());renderMain()}}
const originalFinishBattle=finishBattle;finishBattle=function(enemy){const me=state.monsters.find(x=>monsterId(x,0)===state.selectedMonsterId)||state.monsters.at(-1);const myPower=(me?.stats||[]).reduce((a,s)=>a+Number(s.value||0),0),enemyPower=(enemy.stats||[]).reduce((a,s)=>a+Number(s.value||0),0);originalFinishBattle(enemy);const result=$('battleResult');if(myPower>enemyPower&&me){const available=(me.stats||[]).filter(s=>Number(s.value)<5);if(available.length){available[Math.floor(Math.random()*available.length)].value++;save();result.insertAdjacentHTML('beforeend','<div style="margin-top:12px;color:#125b3c">勝利ボーナス：ランダムなパラメーターが1増えました！</div>')}}if(result&&myPower<enemyPower&&enemy.imageData)result.insertAdjacentHTML('beforeend',`<div style="margin-top:14px">相手が発行した画像</div><img class="monster-img" src="${enemy.imageData}" alt="相手の発行画像">`)};
document.addEventListener('DOMContentLoaded',()=>{applyTrainerWords();$('openSummon').onclick=startMonsterIssue;generateQRs()});

function initialStats(){const values=[1,1,1,3];for(let i=0;i<3;i++){const choices=values.map((v,index)=>index).filter(index=>values[index]<5);const index=choices[Math.floor(Math.random()*choices.length)];values[index]++;}return fixedStatNames.map((name,index)=>({name,value:values[index]}))}
function normalizeStats(stats){if(!(stats||[]).some(s=>fixedStatNames.includes(s.name)))return initialStats();const values=fixedStatNames.map(name=>Math.max(1,Math.min(5,Number((stats||[]).find(s=>s.name===name)?.value||1))));return fixedStatNames.map((name,index)=>({name,value:values[index]}))}
const baseStartMonsterIssue=startMonsterIssue;startMonsterIssue=function(){baseStartMonsterIssue();const submit=$('issueSubmit');if(submit){const oldClick=submit.onclick;submit.onclick=()=>{if(oldClick)oldClick();if(candidate){candidate.stats=initialStats();renderResult()}}}};
const baseRenderMain=renderMain;baseRenderMain;renderMain=function(){state.monsters.forEach(m=>m.stats=normalizeStats(m.stats));baseRenderMain()};
